import glob
import os
import os.path

print('srcTree now in work')

Import('env')
localEnv = env.Clone()
localEnv.Append(CPPPATH=['./include', '../external/GSL/include'])

os.system('pwd')
src = glob.glob('../src/*/*.cpp')

print(src)

localEnv.Library('compiler', src)
localEnv.Program('jaco', ['main.cpp'], LIBS='compiler', LIBPATH='.')

